### ISSUE TITLE
Could you please customize an RSS feed for your blog so that I can subscribe to it?

### ISSUE THREAD

**Issue by cdxiaodong** [thediveo/thediveo.github.io#1]
Could you please customize an RSS feed for your blog so that I can subscribe to it?

**Comment by thediveo** [comment]
I've checked with the [list of docsify plugins](https://docsify.js.org/#/awesome?id=plugins) but there doesn't seem to be RSS support available for docsify; I've very limited understanding about RSS but would suspect that this isn't possible due to the way docsify works. The normal RSS feed for github pages unfortunately seem to work only with the Jekyll mechanism or some other pre-rendering technique. I'm afraid that I can't offer an RSS feed due to these restrictions, as I do not plan to migrate away from docsify.

**Comment by cdxiaodong** [comment]
Okay... That's all we can do now.

**Comment by thediveo** [comment]
After having read a few more pieces, I think that generating and updating the RSS XML file from my source can be semi-automated and would suffice, subject to me forgetting to run the script.

**Comment by thediveo** [comment]
I came up with a bash script to extract front matter information (now finally I have a use for _that_) and added an RSS feed. Enjoy.

**Comment by cdxiaodong** [comment]
nice ，i cannot wait to follow it
![image](https://github.com/user-attachments/assets/6436c77b-3731-4fe4-a6a2-604b6cc180e1)
